# Generated by Django 5.2 on 2025-05-09 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
